[package]
name = "sup"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
argh = "0.1.13"
git2 = "0.20.2"
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0.140"
structopt = "0.3.26"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
openssl = { version = "0.10", features = ["vendored"] }

[dev-dependencies]
tempfile = "3"
