on:
  workflow_dispatch:

jobs:
  package-debian:
    permissions:
      pages: write
      contents: write
    runs-on: ubuntu-latest
    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      KEY_ID: ${{ vars.KEY_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro dpkg-dev curl jq gnupg debsigs

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$KEY_ID:6:" |  gpg --batch --import-ownertrust --pinentry-mode=loopback

      - name: Create APT repository
        run: |
          curl -s https://raw.githubusercontent.com/strowk/sup/main/install.sh | bash
          mkdir -p target/x86_64-unknown-linux-gnu/release
          cp /usr/local/bin/sup target/x86_64-unknown-linux-gnu/release/sup
          version=$(sup --version | awk '{print $3}')
          docker build --build-arg VERSION=${version} -t sup-cargo-deb --cache-from=type=gha --cache-to=type=gha,mode=max -f packages/debian/Dockerfile .
          mkdir -p target/x86_64-unknown-linux-gnu/debian/
          docker run --rm -v $(pwd)/packages/debian:/package sup-cargo-deb bash -c "cat /app/target/x86_64-unknown-linux-gnu/debian/git-sup_${version}-1_amd64.deb" > target/x86_64-unknown-linux-gnu/debian/git-sup_${version}-1_amd64.deb
          debsigs -v --gpgopts="--batch --no-tty --pinentry-mode=loopback" --sign=origin --default-key="$KEY_ID" target/x86_64-unknown-linux-gnu/debian/git-sup_${version}-1_amd64.deb
          mkdir -p repo/conf
          echo "Origin: github.com/strowk/sup" >repo/conf/distributions
          echo "Label: github.com/strowk/sup" >>repo/conf/distributions
          echo "Suite: stable" >>repo/conf/distributions
          echo "Codename: any" >>repo/conf/distributions
          echo "Components: main" >>repo/conf/distributions
          echo "Architectures: amd64" >>repo/conf/distributions
          echo "SignWith: $KEY_ID" >>repo/conf/distributions
          cp target/x86_64-unknown-linux-gnu/debian/git-sup_${version}-1_amd64.deb git-sup_${version}-1_amd64.deb
          reprepro -Vb repo includedeb any "git-sup_${version}-1_amd64.deb"
          gpg --export $KEY_ID > repo/pubkey.gpg
          cp packages/debian/index.html repo/index.html

      - name: Deploy APT repository to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
